version: '3.5'

services:
  pgadmin:
    image: "dpage/pgadmin4:latest"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    links:
      - postgres
    env_file:
      - pgadmin.env
    depends_on:
      - postgres

  postgres:
    image: "postgres:12-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - postgres.env
    # network_mode: bridge

volumes:
  pg_data:
