version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: 
      - pgadmin.env
    ports: 
      - "8080:80"
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    links: 
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: